# -*- coding: utf-8 -*-
"""
/***************************************************************************
 center_select
                                 A QGIS plugin
 Center and select features from a vector layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-04
        copyright            : (C) 2022 by SbasGM
        email                : sbasglzmir@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load center_select class from file center_select.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .center_select import center_select
    return center_select(iface)
